### ISSUE TITLE
Puppet 5 support

### ISSUE THREAD

**Issue by titansmc** [cernops/puppet-slurm#9]
Hi,
I met you guys at the SLURM UGM in Madrid and I am gonna try the module, but we are running puppet 5, should I expect it to work?

Cheers.

**Comment by pllopis** [comment]
Hello sorry for the very late reply. For reference, yes, in fact we're running it with Puppet 5.
Did you find the module useful? We're still using it and will be updating the upstream code more often.

**Comment by titansmc** [comment]
sorry Pablo for the late reply, I stepped in to another project. I will give it a try once back to slurm.

**Comment by pllopis** [comment]
Sure, let me know how it goes.
Cheers
